FROM node:16.15.0

ENV NODE_ENV=uat
WORKDIR /app

EXPOSE 5111
EXPOSE 5500

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --production

COPY . .
# COPY ["uat.docker.env", "uat.env"]
CMD [ "node", "app.js" ]



